"""Markdown reporter — generates human-readable production-readiness reports.

The Markdown output is designed for:
  - README demos (show what FailFast produces)
  - PR comments (paste into GitHub/GitLab PR reviews)
  - Documentation (include scan results in project docs)
"""

from __future__ import annotations

from failfast.models import Category, Finding, Scorecard, Verdict


def to_markdown(scorecard: Scorecard) -> str:
    """Generate a Markdown report from a Scorecard.

    Args:
        scorecard: The scan result to render.

    Returns:
        A complete Markdown document as a string.
    """
    lines: list[str] = []

    # Header
    lines.append("# FailFast Production Readiness Report")
    lines.append("")

    # Verdict badge
    verdict_emoji = _verdict_emoji(scorecard.verdict)
    lines.append(f"**Verdict:** {verdict_emoji} **{scorecard.verdict.value.upper()}**")
    lines.append("")
    lines.append(f"> {scorecard.summary}")
    lines.append("")

    # Metadata
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Path | `{scorecard.scan_path}` |")
    lines.append(f"| Profile | `{scorecard.profile}` |")
    lines.append(f"| Blockers | {len(scorecard.blockers)} |")
    lines.append(f"| Warnings | {len(scorecard.warnings)} |")
    lines.append(f"| Total Findings | {len(scorecard.all_findings)} |")
    lines.append("")

    # Category summary
    lines.append("## Category Summary")
    lines.append("")
    lines.append("| Category | Verdict | Blockers | Warnings |")
    lines.append("|---|:---:|:---:|:---:|")

    for cat in Category:
        result = scorecard.categories.get(cat)
        if result:
            emoji = _verdict_emoji(result.verdict)
            lines.append(
                f"| {cat.value} | {emoji} {result.verdict.value.upper()} "
                f"| {result.blocker_count} | {result.warning_count} |"
            )
        else:
            lines.append(f"| {cat.value} | ✅ PASS | 0 | 0 |")

    lines.append("")

    # Blockers section
    if scorecard.blockers:
        lines.append("## ⛔ Blockers")
        lines.append("")
        lines.append("These issues **must be resolved** before code is production-ready.")
        lines.append("")

        for i, finding in enumerate(scorecard.blockers, 1):
            lines.extend(_render_finding(i, finding, is_blocker=True))

    # Warnings section
    if scorecard.warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        lines.append("These issues should be reviewed but are not blocking.")
        lines.append("")

        for i, finding in enumerate(scorecard.warnings, 1):
            lines.extend(_render_finding(i, finding, is_blocker=False))

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by [FailFast Developer MCP]"
        "(https://github.com/MErblin/failfast-developer-mcp) "
        "— Production-readiness reviewer for Python code.*"
    )
    lines.append("")

    return "\n".join(lines)


def _verdict_emoji(verdict: Verdict) -> str:
    """Map verdict to an emoji."""
    return {
        Verdict.PASS: "✅",
        Verdict.FAIL: "❌",
        Verdict.WARN: "⚠️",
    }.get(verdict, "❓")


def _render_finding(index: int, finding: Finding, *, is_blocker: bool) -> list[str]:
    """Render a single finding as Markdown lines."""
    lines: list[str] = []
    marker = "⛔" if is_blocker else "⚠️"

    lines.append(f"### {index}. {marker} {finding.title}")
    lines.append("")
    lines.append(f"- **ID:** `{finding.id}`")
    lines.append(f"- **Severity:** {finding.severity.value}")
    lines.append(f"- **Category:** {finding.category.value}")
    lines.append(f"- **File:** `{finding.file_path}:{finding.line}`")
    lines.append("")

    if finding.evidence:
        lines.append("**Evidence:**")
        lines.append("```python")
        lines.append(finding.evidence)
        lines.append("```")
        lines.append("")

    lines.append(f"**Why this matters:** {finding.why}")
    lines.append("")
    lines.append(f"**How to fix:** {finding.fix}")
    lines.append("")

    if finding.standard_refs:
        refs = ", ".join(f"`{ref}`" for ref in finding.standard_refs)
        lines.append(f"**Standards:** {refs}")
        lines.append("")

    return lines
